version: '3.8'

services:
    server:
        build:
            context: ./server
        container_name: server
        ports:
            - 80:80
        networks:
            - shared-net
        volumes:
            - type: bind
              source: ./server/httpd.conf
              target: /usr/local/apache2/conf/httpd.conf
    front:
        build:
            context: ./front
        container_name: front
        ports:
            - 3000:3000
        networks:
            - shared-net
        volumes:
            - type: bind
              source: ./front/app
              target: /usr/src/app
        tty: true
        stdin_open: true
    api:
        build:
            context: ./api
        container_name: api
        ports:
            - 5000:5000
        networks:
            - shared-net
        volumes:
            - type: bind
              source: ./api/app
              target: /usr/src/app
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - TZ=Asia/Tokyo
    db:
        build:
            context: ./db
        container_name: db
        ports:
            - 5432:5432
        networks:
            - shared-net
        volumes:
            - type: bind
              source: ./db/data
              target: /var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - TZ=Asia/Tokyo

networks:
    shared-net:
        external: true
