version: '3.8'

services:
    server:
        build:
            context: ./server
        container_name: server
        ports:
            - 80:80
        networks:
            - shared-net

networks:
    shared-net:
        external: true
