version: '3.8'

services:
    server:
        build:
            context: ./server
        container_name: server
        ports:
            - 80:80
        networks:
            - shared-net
        volumes:
            -type: bind
            source: ./server/httpd.conf
            target: /usr/local/apache2/conf/httpd.conf

networks:
    shared-net:
        external: true
